SeeSharpSoft/intellij-csv-validator

src/main/java/net/seesharpsoft/intellij/plugins/csv/CsvAnnotator.java, src/main/java/net/seesharpsoft/intellij/plugins/csv/CsvHelper.java, src/main/java/net/seesharpsoft/intellij/plugins/csv/intention/CsvIntentionHelper.java, src/main/java/net/seesharpsoft/intellij/plugins/csv/intention/CsvQuoteAllIntentionAction.java, src/main/java/net/seesharpsoft/intellij/plugins/csv/intention/CsvQuoteValueIntentionAction.java, src/main/java/net/seesharpsoft/intellij/plugins/csv/intention/CsvShiftColumnLeftIntentionAction.java, src/main/java/net/seesharpsoft/intellij/plugins/csv/intention/CsvShiftColumnRightIntentionAction.java, src/main/java/net/seesharpsoft/intellij/plugins/csv/intention/CsvUnquoteAllIntentionAction.java, src/main/java/net/seesharpsoft/intellij/plugins/csv/intention/CsvUnquoteValueIntentionAction.java, src/main/java/net/seesharpsoft/intellij/plugins/csv/intention/CsvValidationInspection.java, src/main/java/net/seesharpsoft/intellij/plugins/csv/structureview/CsvStructureViewElement.java, src/main/resources/META-INF/plugin.xml, src/test/java/net/seesharpsoft/intellij/plugins/csv/CsvAnnotatorTest.java, src/test/resources/AnnotatorTestData.csv
=> [FEATURE] CSV Annotator added

src/main/java/net/seesharpsoft/intellij/plugins/csv/CsvAnnotator.java, src/main/java/net/seesharpsoft/intellij/plugins/csv/CsvColumnInfoMap.java, src/main/java/net/seesharpsoft/intellij/plugins/csv/CsvHelper.java, src/main/java/net/seesharpsoft/intellij/plugins/csv/formatter/CsvFormattingInfo.java, src/main/java/net/seesharpsoft/intellij/plugins/csv/highlighter/CsvHighlightUsagesHandler.java, src/main/java/net/seesharpsoft/intellij/plugins/csv/highlighter/CsvHighlightUsagesHandlerFactory.java, src/main/java/net/seesharpsoft/intellij/plugins/csv/intention/CsvShiftColumnLeftIntentionAction.java, src/main/java/net/seesharpsoft/intellij/plugins/csv/intention/CsvShiftColumnRightIntentionAction.java, src/main/java/net/seesharpsoft/intellij/plugins/csv/psi/CsvFile.java, src/main/java/net/seesharpsoft/intellij/plugins/csv/structureview/CsvStructureViewElement.java, src/main/resources/META-INF/plugin.xml, src/test/java/net/seesharpsoft/intellij/plugins/csv/CsvAnnotatorTest.java, src/test/java/net/seesharpsoft/intellij/plugins/csv/highlighter/CsvHighlightUsagesHandlerTest.java, src/test/resources/AnnotatorTestData.csv, src/test/resources/highlighter/HighlightUsagesTestData01.csv, src/test/resources/highlighter/HighlightUsagesTestData02.csv, src/test/resources/highlighter/HighlightUsagesTestData03.csv, src/test/resources/highlighter/HighlightUsagesTestData04.csv, src/test/resources/highlighter/HighlightUsagesTestData05.csv, src/test/resources/highlighter/HighlightUsagesTestData06.csv
- includes several code reworks for better re-use and improved performance
Fixes #30
=> [FEATURE] CSV Usages Handler added

src/main/java/net/seesharpsoft/intellij/plugins/csv/settings/CsvCodeStyleSettingsProvider.java, src/main/java/net/seesharpsoft/intellij/plugins/csv/settings/CsvLanguageCodeStyleSettingsProvider.java
=> [FEATURE] custom wrapping settings for CSV

src/main/java/net/seesharpsoft/intellij/plugins/csv/CsvAnnotator.java, src/test/java/net/seesharpsoft/intellij/plugins/csv/CsvAnnotatorTest.java, src/test/resources/AnnotatorTestData.csv
=> [FIX] higher priority for CSV tooltips than for spellchecker

src/main/java/net/seesharpsoft/intellij/plugins/csv/editor/table/swing/CsvTableEditorSwing.form, src/main/java/net/seesharpsoft/intellij/plugins/csv/editor/table/swing/CsvTableEditorSwing.java
=> [FIX] top and bottom panel scrollable & add column/row buttons removed

src/main/java/net/seesharpsoft/intellij/plugins/csv/CsvHelper.java, src/main/java/net/seesharpsoft/intellij/plugins/csv/editor/CsvEditorSettingsExternalizable.java, src/main/java/net/seesharpsoft/intellij/plugins/csv/editor/CsvEditorSettingsProvider.form, src/main/java/net/seesharpsoft/intellij/plugins/csv/editor/CsvEditorSettingsProvider.java, src/main/java/net/seesharpsoft/intellij/plugins/csv/editor/table/CsvTableEditor.java, src/test/java/net/seesharpsoft/intellij/plugins/csv/editor/CsvEditorSettingsProviderTest.java, src/test/java/net/seesharpsoft/intellij/plugins/csv/editor/table/swing/CsvTableEditorSwingTest.java, src/test/resources/editor/TableEditorFileChanged.csv, src/test/resources/editor/TableEditorFileChangedQuoted.csv
=> [FEATURE] table-editor: setting to toggle enforced value quoting

src/main/java/net/seesharpsoft/intellij/plugins/csv/editor/table/CsvTableEditor.java, src/main/java/net/seesharpsoft/intellij/plugins/csv/editor/table/swing/CsvTableEditorKeyListener.java, src/main/java/net/seesharpsoft/intellij/plugins/csv/editor/table/swing/CsvTableEditorSwing.java, src/test/java/net/seesharpsoft/intellij/plugins/csv/editor/table/swing/CsvTableEditorKeyListenerTest.java
=> [FIX] prevent backspace/delete erasing cell value while editing

src/main/java/net/seesharpsoft/intellij/plugins/csv/editor/table/swing/CsvTableEditorMouseListener.java
=> [FIX] skip column selection if pressed outside a column

src/main/java/net/seesharpsoft/intellij/plugins/csv/CsvHelper.java, src/main/java/net/seesharpsoft/intellij/plugins/csv/editor/CsvFileEditorProvider.java, src/main/java/net/seesharpsoft/intellij/plugins/csv/editor/table/CsvTableEditorProvider.java
=> [FEATURE] support for ScratchFileType

src/main/java/net/seesharpsoft/intellij/plugins/csv/editor/table/CsvTableEditor.java, src/main/java/net/seesharpsoft/intellij/plugins/csv/editor/table/swing/CsvTableEditorActions.java, src/test/java/net/seesharpsoft/intellij/plugins/csv/editor/table/swing/CsvTableEditorActionsTest.java, src/test/java/net/seesharpsoft/intellij/plugins/csv/editor/table/swing/CsvTableEditorKeyListenerTest.java
=> [INTERNAL] move add/remove row/column functionality to CsvTableEditor

src/main/java/net/seesharpsoft/intellij/plugins/csv/editor/table/swing/MultiLineCellRenderer.java
=> [FIX] use CopyOnWriteArraySet to avoid ConcurrentModificationException

src/main/java/net/seesharpsoft/intellij/plugins/csv/editor/table/CsvTableEditor.java
=> [FIX] AssertionError: Already disposed: Project (Disposed)

src/main/java/net/seesharpsoft/intellij/plugins/csv/editor/table/CsvTableEditor.java, src/main/java/net/seesharpsoft/intellij/plugins/csv/editor/table/swing/CsvTableEditorActions.java
=> [FIX] Index out of bound error on multi line clear cells

src/main/java/net/seesharpsoft/intellij/plugins/csv/editor/table/swing/CsvTableEditorMouseWheelListener.java, src/test/java/net/seesharpsoft/intellij/plugins/csv/editor/table/swing/CsvTableEditorMouseWheelListenerTest.java
=> [INTERNAL] table editor horizontal scrolling

src/main/java/net/seesharpsoft/intellij/plugins/csv/CsvValueSeparator.java, src/main/java/net/seesharpsoft/intellij/plugins/csv/components/CsvFileAttributes.java, src/main/java/net/seesharpsoft/intellij/plugins/csv/psi/CsvFile.java, src/main/java/net/seesharpsoft/intellij/plugins/csv/settings/CsvEditorSettings.java
=> [FIX] handle separator in EditorSettings correct & refresh CsvFile

CHANGELOG, build.gradle, src/main/java/net/seesharpsoft/intellij/plugins/csv/CsvCommenter.java, src/main/resources/META-INF/plugin.xml
=> [NEW] Support "Comment with line comment"

CHANGELOG, README.md, src/main/java/net/seesharpsoft/intellij/plugins/csv/editor/table/CsvTableEditorState.java, src/main/java/net/seesharpsoft/intellij/plugins/csv/psi/CsvFile.java, src/main/java/net/seesharpsoft/intellij/plugins/csv/settings/CsvEditorSettings.java, src/main/java/net/seesharpsoft/intellij/plugins/csv/settings/CsvEditorSettingsProvider.form, src/main/java/net/seesharpsoft/intellij/plugins/csv/settings/CsvEditorSettingsProvider.java, src/main/resources/META-INF/plugin.xml, src/test/java/net/seesharpsoft/intellij/plugins/csv/settings/CsvEditorSettingsProviderTest.java
Fix "Value Coloring" not applied to open files
=> [NEW] default "Header row fixed" setting

.travis.yml, build.gradle, src/main/java/net/seesharpsoft/intellij/plugins/csv/CsvPlugin.java, src/main/java/net/seesharpsoft/intellij/plugins/csv/editor/CsvAnnotator.java, src/main/java/net/seesharpsoft/intellij/plugins/psv/PsvFileType.java, src/main/java/net/seesharpsoft/intellij/plugins/tsv/TsvFileType.java
- further cleanup with respect to code deprecation & internal code usage
=> [FIX] annotator fix

.github/workflows/PullRequest.yml, CHANGELOG, build.gradle, src/main/java/net/seesharpsoft/intellij/plugins/csv/CsvStorageHelper.java, src/main/resources/META-INF/plugin.xml, src/test/java/net/seesharpsoft/intellij/plugins/csv/CsvStorageHelperTest.java, src/test/java/net/seesharpsoft/intellij/plugins/csv/components/CsvFileAttributesTest.java
=> [FIX] keep existing & correct entries in CSV attributes map

CHANGELOG, build.gradle, src/main/java/net/seesharpsoft/intellij/plugins/csv/CsvHelper.java, src/main/java/net/seesharpsoft/intellij/plugins/csv/components/CsvFileAttributes.java, src/main/resources/META-INF/plugin.xml
=> check filetype by extension only (performance is key, avoid reading the file itself)

src/main/java/net/seesharpsoft/intellij/plugins/csv/psi/CsvFile.java, src/main/java/net/seesharpsoft/intellij/plugins/csv/psi/CsvPsiReferenceContributor.java, src/main/resources/META-INF/plugin.xml
=> Ability to open urls from IntelliJ csv view

.github/workflows/CIBuild.yml, .github/workflows/CronEAP.yml, .github/workflows/PublishStable.yml, .github/workflows/PullRequest.yml, build.gradle, gradle/wrapper/gradle-wrapper.properties, src/main/java/net/seesharpsoft/intellij/plugins/csv/editor/table/CsvTableEditor.java
update gradle build & github actions
=> [FIX] Cannot load from object array because "data" is null

CHANGELOG, build.gradle, src/main/java/net/seesharpsoft/intellij/plugins/csv/CsvEscapeCharacter.java, src/main/java/net/seesharpsoft/intellij/plugins/csv/CsvStorageHelper.java, src/main/java/net/seesharpsoft/intellij/plugins/csv/components/CsvFileAttributes.java, src/main/resources/META-INF/plugin.xml
FIX: cannot init component state (componentName=CsvFileAttributes) #359
FIX: image in plugin description
FIX: plugin update restart
=> Release 3.0.1

.github/workflows/PublishStable.yml, CHANGELOG, build.gradle, src/test/java/net/seesharpsoft/intellij/plugins/csv/CsvBasePlatformTestCase.java, src/test/java/net/seesharpsoft/intellij/plugins/csv/CsvHelperTest.java, src/test/java/net/seesharpsoft/intellij/plugins/csv/CsvStorageHelperTest.java, src/test/java/net/seesharpsoft/intellij/plugins/csv/actions/CsvActionTestBase.java, src/test/java/net/seesharpsoft/intellij/plugins/csv/components/CsvFileAttributesTest.java, src/test/java/net/seesharpsoft/intellij/plugins/csv/editor/CsvAnnotatorTest.java, src/test/java/net/seesharpsoft/intellij/plugins/csv/editor/CsvFileEditorTest.java, src/test/java/net/seesharpsoft/intellij/plugins/csv/editor/table/CsvTableEditorProviderTest.java, src/test/java/net/seesharpsoft/intellij/plugins/csv/editor/table/CsvTableEditorStateTest.java, src/test/java/net/seesharpsoft/intellij/plugins/csv/editor/table/CsvTableModelBaseTest.java, src/test/java/net/seesharpsoft/intellij/plugins/csv/editor/table/ExpectedHighlightingDataWrapper.java, src/test/java/net/seesharpsoft/intellij/plugins/csv/editor/table/swing/CsvMultiLineCellRendererTest.java, src/test/java/net/seesharpsoft/intellij/plugins/csv/editor/table/swing/CsvTableCommentsAtBeginningTest.java, src/test/java/net/seesharpsoft/intellij/plugins/csv/editor/table/swing/CsvTableEditorChangeListenerTest.java, src/test/java/net/seesharpsoft/intellij/plugins/csv/editor/table/swing/CsvTableEditorMouseWheelListenerTest.java, src/test/java/net/seesharpsoft/intellij/plugins/csv/editor/table/swing/CsvTableEditorSwingTest.java, src/test/java/net/seesharpsoft/intellij/plugins/csv/editor/table/swing/CsvTableEditorSwingTestBase.java, src/test/java/net/seesharpsoft/intellij/plugins/csv/formatter/CsvFormatterTest.java, src/test/java/net/seesharpsoft/intellij/plugins/csv/highlighter/CsvHighlightUsagesHandlerTest.java, src/test/java/net/seesharpsoft/intellij/plugins/csv/inspection/CsvInspectionTest.java, src/test/java/net/seesharpsoft/intellij/plugins/csv/intention/CsvIntentionTest.java, src/test/java/net/seesharpsoft/intellij/plugins/csv/settings/CsvEditorSettingsProviderTest.java, src/test/java/net/seesharpsoft/intellij/plugins/csv/settings/CsvEditorSettingsTest.java, src/test/java/net/seesharpsoft/intellij/plugins/tsv/inspection/TsvInspectionTest.java
NEW: add support for upcoming IntelliJ version 2023.2.*
FIX: broken tests
=> Release 3.2.1

.github/workflows/PublishStable.yml, CHANGELOG, build.gradle, src/main/java/net/seesharpsoft/intellij/plugins/csv/CsvGithubIssueSubmitter.java, src/main/java/net/seesharpsoft/intellij/plugins/csv/editor/table/swing/CsvTable.java, src/main/java/net/seesharpsoft/intellij/plugins/csv/editor/table/swing/CsvTableEditorSwing.java, src/main/java/net/seesharpsoft/intellij/plugins/csv/psi/CsvPsiTreeUpdater.java, src/main/java/net/seesharpsoft/intellij/plugins/csv/settings/CsvEditorSettingsProvider.java
FIX: NullPointerException: Cannot invoke "getSelectedColumn()" because "tblEditor" is null #519
FIX: IllegalStateException: Attempt to modify PSI for non-committed Document! #516
FIX: StringIndexOutOfBoundsException: begin 0, end -1, length 5995 #511
FIX: ArrayIndexOutOfBoundsException: 12 >= 12 #482
=> Fix release 3.2.2

CHANGELOG, build.gradle, src/main/java/net/seesharpsoft/intellij/plugins/csv/CsvGithubIssueSubmitter.java, src/test/java/net/seesharpsoft/intellij/plugins/csv/CsvGithubIssueSubmitterTest.java
NEW: Prevent github issue submitter spam
FIX: Improve issue duplicate finder
=> Release 3.2.3
